// <auto-generated />
using System;
using CustomerServiceCampaign.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerServiceCampaign.Api.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    partial class CampaignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("CustomerServiceCampaign.Api.Models.CampaignReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PurchaseSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RewardDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CampaignRewards");
                });
#pragma warning restore 612, 618
        }
    }
}
